# Generated by Django 4.2.3 on 2023-08-09 13:35

import dental_clinic.patient.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30, validators=[dental_clinic.patient.validators.validate_name_start_with_capital_letter, dental_clinic.patient.validators.validate_name_contain_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[dental_clinic.patient.validators.validate_name_start_with_capital_letter, dental_clinic.patient.validators.validate_name_contain_only_letters])),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), dental_clinic.patient.validators.validate_phone_number_only_nums])),
                ('treatment', models.ManyToManyField(blank=True, to='treatment.treatment')),
            ],
        ),
    ]
