# Generated by Django 4.2.3 on 2023-08-07 13:23

import dental_clinic.patient.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=30, validators=[dental_clinic.patient.validators.validate_name_start_with_capital_letter, dental_clinic.patient.validators.validate_name_contain_only_letters]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=30, validators=[dental_clinic.patient.validators.validate_name_start_with_capital_letter, dental_clinic.patient.validators.validate_name_contain_only_letters]),
        ),
    ]
