# Generated by Django 4.2.3 on 2026-07-21 13:22

import dental_clinic.patient.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[dental_clinic.patient.validators.validate_date_not_in_future]),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            # NOTE: intentionally no `unique`/`default` here. Adding a callable
            # default alongside a unique constraint in one AddField makes
            # Postgres evaluate the callable ONCE and backfill every existing
            # row with the SAME value, so the unique index creation fails on
            # any populated table. 0003 backfills distinct values per row,
            # then 0004 applies `unique=True` + the real default once every
            # row already holds a distinct patient_id.
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
