# Generated by Django 4.2.3 on 2026-07-21 13:23

import uuid

from django.db import migrations, transaction
from django.db.utils import IntegrityError

PATIENT_ID_PREFIX = 'PT-'
MAX_ATTEMPTS = 10


def _generate_patient_id():
    return f"{PATIENT_ID_PREFIX}{uuid.uuid4().hex[:8].upper()}"


def populate_patient_ids(apps, schema_editor):
    Patient = apps.get_model('patient', 'Patient')

    for patient in Patient.objects.filter(patient_id__isnull=True):
        for attempt in range(MAX_ATTEMPTS):
            patient.patient_id = _generate_patient_id()
            try:
                # Wrapped in its own savepoint so a collision only rolls back
                # this attempt, not the whole migration transaction (Postgres
                # aborts the enclosing transaction on IntegrityError).
                with transaction.atomic():
                    patient.save(update_fields=['patient_id'])
                break
            except IntegrityError:
                if attempt == MAX_ATTEMPTS - 1:
                    raise


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_enrichment'),
    ]

    operations = [
        migrations.RunPython(populate_patient_ids, migrations.RunPython.noop),
    ]
