# Generated by Django 4.2.3 on 2026-07-21 13:23

import dental_clinic.patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_populate_patient_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=dental_clinic.patient.models.generate_patient_id, editable=False, max_length=11, unique=True),
        ),
    ]
