# Generated by Django 4.2.3 on 2026-07-21 13:24

import dental_clinic.patient.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_id_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, validators=[dental_clinic.patient.validators.validate_date_not_in_future])),
                ('note', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_entries', to='patient.patient')),
            ],
            options={
                'ordering': ('-entry_date',),
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=8)),
                ('diagnosed_date', models.DateField(blank=True, null=True, validators=[dental_clinic.patient.validators.validate_date_not_in_future])),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='patient.patient')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=8)),
                ('reaction', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patient.patient')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
