# Generated by Django 4.2.3 on 2026-07-21 14:21

from django.db import migrations

BACKFILL_NOTE = 'Migrated from legacy treatment list'


def backfill_treatment_records(apps, schema_editor):
    Patient = apps.get_model('patient', 'Patient')
    TreatmentRecord = apps.get_model('patient', 'TreatmentRecord')

    for patient in Patient.objects.all().prefetch_related('treatment'):
        for treatment in patient.treatment.all():
            # get_or_create keyed on (patient, treatment, notes) makes this
            # idempotent: re-running the forward op (fake-back + reapply,
            # squash replay, restore-then-migrate) will not duplicate the
            # legacy records already backfilled.
            TreatmentRecord.objects.get_or_create(
                patient=patient,
                treatment=treatment,
                notes=BACKFILL_NOTE,
                defaults={'date_performed': None},
            )


def remove_backfilled_treatment_records(apps, schema_editor):
    # The reverse op identifies backfilled rows solely by the BACKFILL_NOTE
    # marker text (there is no dedicated schema column for it, since this is
    # a one-time migration and adding one would be disproportionate).
    # Because the forward op is keyed on (patient, treatment, notes) via
    # get_or_create, each legacy (patient, treatment) pair maps to at most
    # one such row, so the pairing is unique.
    # Residual risk (accepted): any record a user manually creates with
    # notes exactly equal to BACKFILL_NOTE will also be deleted on unapply.
    # Manually creating a record with that exact note text is unsupported.
    TreatmentRecord = apps.get_model('patient', 'TreatmentRecord')
    TreatmentRecord.objects.filter(notes=BACKFILL_NOTE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_medicalcondition_code_treatmentrecord_prescription_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_treatment_records, remove_backfilled_treatment_records),
    ]
