# Generated by Django 4.2.3 on 2023-07-22 16:08

import dental_clinic.treatment.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3), dental_clinic.treatment.validators.validate_contain_only_digits])),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
