# Generated by Django 4.2.3 on 2026-07-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
