# Generated by Django 4.2.3 on 2023-08-07 13:23

import dental_clinic.treatment.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='clinical_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), dental_clinic.treatment.validators.validate_contain_only_digits]),
        ),
    ]
