# Generated by Django 4.2.3 on 2023-08-09 13:35

import dental_clinic.dentist_profile.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistUserProfile',
            fields=[
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), dental_clinic.dentist_profile.validators.validate_name_contain_only_letters, dental_clinic.dentist_profile.validators.validate_name_start_with_capital_letter])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), dental_clinic.dentist_profile.validators.validate_name_contain_only_letters, dental_clinic.dentist_profile.validators.validate_name_start_with_capital_letter])),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
